version: '3'

services:
  backend:
    image: hkow/clickbackend
    expose:
      - "3000"

  frontend:
    image: hkow/clickfrontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Nginx configuration file
